http:
  routers:
    # Entrypoint via Cloudflare Tunnel
    ${SERVICE}_public:
      rule: Host(`${SUBDOMAIN}.${DOMAIN}`) && Path(`/`)
      entrypoints:
        - web
      middlewares:
        - mark-as-hopped
        - security-headers
      service: ${SERVICE}_public

    # Final Mesh Entrypoint (for load balancing)
    ${SERVICE}_mesh_public:
      rule: "Host(`${SUBDOMAIN}.${DOMAIN}`) && Path(`/`) && Header(`X-Mesh-Hops`, `1`)"
      entrypoints:
        - web
      priority: 200
      service: ${SERVICE}_local_public

  services:
    # Final Mesh service
    ${SERVICE}_local_public:
      loadBalancer:
        servers:
          - url: http://${SERVICE}:${PORT}
    # Loadbalanced services
    ${SERVICE}_public:
      loadBalancer:
        servers: [ ${LOAD_BALANCED_SERVERS} ]