http:
  routers:
    # Entrypoint via Tailscale
    ${SERVICE}_${SUBDOMAIN}_internal_${POOL_TAG}:
      rule: Host(`${SUBDOMAIN}.int.${DOMAIN}`) && PathPrefix(`/`) && Query(`x-tag`, `${POOL_TAG}`)
      entrypoints:
        - websecure
      middlewares:
        - security-headers
        - tailscale-only
        - mark-as-hopped
      priority: 300
      service: ${SERVICE}_${SUBDOMAIN}_internal_${POOL_TAG}
      tls: {}

  services:
    # Loadbalanced pool services
    ${SERVICE}_${SUBDOMAIN}_internal_${POOL_TAG}:
      loadBalancer:
        servers: [ ${LOAD_BALANCED_SERVERS} ]