http:
  routers:
    # Entrypoint via Tailscale
    ${SERVICE}_internal:
      rule: Host(`${SERVICE}.int.${DOMAIN}`) && Path(`/`)
      entrypoints:
        - websecure
      middlewares:
        - mark-as-hopped
        - tailscale-only
      service: ${SERVICE}
      tls:
        certResolver: cloudflare

    # Entrypoint via Cloudflare Tunnel
    ${SERVICE}_public:
      rule: Host(`${SERVICE}.${DOMAIN}`) && Path(`/`)
      entrypoints:
        - web
      middlewares:
        - mark-as-hopped
        - security-headers
      service: ${SERVICE}

    # Final Mesh Entrypoint (for load balancing)
    ${SERVICE}_mesh:
      rule: "(Host(`${SERVICE}.${DOMAIN}`) || Host(`${SERVICE}.int.${DOMAIN}`)) && Path(`/`) && Header(`X-Mesh-Hops`, `1`)"
      entrypoints:
        - web
        - websecure
      priority: 200
      service: ${SERVICE}_local

  services:
    # Final Mesh service
    ${SERVICE}_local:
      loadBalancer:
        servers:
          - url: http://${SERVICE}:${PORT}
    # Loadbalanced services
    ${SERVICE}:
      loadBalancer:
        servers:
          - url: http://${SERVICE}:${PORT}