http:
  routers:
    # Discovery endpoint exposing all configured domain tags for this service.
    ${SERVICE}_${SUBDOMAIN}_internal_x_tag:
      rule: Host(`${SUBDOMAIN}.int.${DOMAIN}`) && Path(`/x-tag`) && Method(`GET`)
      entrypoints:
        - websecure
      middlewares:
        - security-headers
        - tailscale-only
        - ${SERVICE}_${SUBDOMAIN}_internal_x_tag_header
      priority: 400
      service: ping@internal
      tls:
        certResolver: cloudflare

    # Entrypoint via Tailscale
    ${SERVICE}_${SUBDOMAIN}_internal:
      rule: Host(`${SUBDOMAIN}.int.${DOMAIN}`) && PathPrefix(`/`)
      entrypoints:
        - websecure
      middlewares:
        - security-headers
        - tailscale-only
        - mark-as-hopped
      service: ${SERVICE}_${SUBDOMAIN}_internal
      tls:
        certResolver: cloudflare

    # Final Mesh Entrypoint (for load balancing)
    ${SERVICE}_${SUBDOMAIN}_mesh_internal:
      rule: "Host(`${SUBDOMAIN}.int.${DOMAIN}`) && PathPrefix(`/`) && Header(`X-Mesh-Hops`, `1`)"
      entrypoints:
        - mesh
      middlewares:
        - server-header
      priority: 200
      service: ${SERVICE}_${SUBDOMAIN}_local_internal

  middlewares:
    ${SERVICE}_${SUBDOMAIN}_internal_x_tag_header:
      headers:
        customResponseHeaders:
          X-Tag: '${DOMAIN_TAGS_HEADER}'

  services:
    # Final Mesh service
    ${SERVICE}_${SUBDOMAIN}_local_internal:
      loadBalancer:
        servers:
          - url: http://${SERVICE}:${PORT}
    # Loadbalanced services
    ${SERVICE}_${SUBDOMAIN}_internal:
      loadBalancer:
        servers: [ ${LOAD_BALANCED_SERVERS} ]