http:
  routers:
    # Discovery endpoint exposing all configured domain tags for this service.
    ${SERVICE}_${SUBDOMAIN}_public_x_tag:
      rule: Host(`${SUBDOMAIN}.${DOMAIN}`) && Path(`/x-tag`) && Method(`GET`)
      entrypoints:
        - web
      middlewares:
        - security-headers
        - ${SERVICE}_${SUBDOMAIN}_public_x_tag_header
      priority: 400
      service: ping@internal

    # Entrypoint via Cloudflare Tunnel
    ${SERVICE}_public:
      rule: Host(`${SUBDOMAIN}.${DOMAIN}`) && Path(`/`)
      entrypoints:
        - web
      middlewares:
        - security-headers
        - mark-as-hopped
      service: ${SERVICE}_public

    # Final Mesh Entrypoint (for load balancing)
    ${SERVICE}_mesh_public:
      rule: "Host(`${SUBDOMAIN}.${DOMAIN}`) && Path(`/`) && Header(`X-Mesh-Hops`, `1`)"
      entrypoints:
        - mesh
      middlewares:
        - server-header
      priority: 200
      service: ${SERVICE}_local_public

  middlewares:
    ${SERVICE}_${SUBDOMAIN}_public_x_tag_header:
      headers:
        customResponseHeaders:
          X-Tag: '${DOMAIN_TAGS_HEADER}'

  services:
    # Final Mesh service
    ${SERVICE}_local_public:
      loadBalancer:
        servers:
          - url: http://${SERVICE}:${PORT}
    # Loadbalanced services
    ${SERVICE}_public:
      loadBalancer:
        servers: [ ${LOAD_BALANCED_SERVERS} ]