accessLog:
  format: json
  filePath: /dev/stdout

ping:
  manualRouting: true

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      # Trust the internal Docker network so Traefik processes the headers
      trustedIPs:
        - "127.0.0.1/32"
        - "172.16.0.0/12" # Cover all default Docker bridge ranges
        - "100.64.0.0/10" # Trust Tailscale range if you're hitting via TS
  websecure:
    address: :443
  mesh:
    address: :9002

certificatesResolvers:
  cloudflare:
    acme:
      email: ${ADMIN_EMAIL}
      storage: /etc/traefik/acme.json