services:
  ${APPLICATION_NAME}:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    networks:
      - sage_default

networks:
  sage_default:
    external: true