services:
  ${APPLICATION_NAME}:
    build:
      context: ${REPO}
      dockerfile: ${DOCKERFILE}
      env_file: build.args
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    networks:
      - sage_default

networks:
  sage_default:
    external: true