services:
  ${CONTAINER_NAME}:
    build:
      context: ${REPO}
      dockerfile: ${DOCKERFILE}
      args: [ ${BUILD_ARGS} ]
      secrets: [ ${BUILD_SECRETS} ]
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    command: ${COMMAND}
    volumes: [ ${VOLUMES} ]
    env_file: .env
    networks:
      - sage_default

networks:
  sage_default:
    external: true

${SECRETS_BLOCK}
